import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Image
      className='styles.landingImage'
      src="https://media.istockphoto.com/id/1300296030/photo/tropical-beach-palm-trees-sea-wave-and-white-sand.jpg?b=1&s=170667a&w=0&k=20&c=4BO9Ro0zHCUdTvEazaG3HEtz08NvNjnLBfvniCgrSJA="
      // alt="background"
      // layout='fill'
      // objectFit='cover'
      // objectPosition='center'
      /> */}
      <Head>
        <title>TIRA's voyage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue a TIRA voyage<a href="https://nextjs.org"></a>
        </h1>

        <p className={styles.description}>
          Nous sommes a votre disposition 24/7
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2> Reservation de billets d'avion &rarr;</h2>
            <p>Retrouvez ici nos diffrentes offres de voyages partout dans le monde</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Location de voiture a destination &rarr;</h2>
            <p>Retrouvez ici nos diffrentes offres de voyages sur l'Amerique</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Reservation d'hotel &rarr;</h2>
            <p>Retrouvez ici nos diffrentes offres de voyages sur l'Amerique</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Nous contacter &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
